baseURL = 'http://qb33.github.io/'
languageCode = 'en-us'
title = 'Welcome to Wonderland'

theme = 'virgo'

hasCJKLanguage = true
summaryLength = 80
paginate = 11
enableGitInfo = true

[params]
    author = 'Qiuyu Bao'
    slogan = 'I Just Cannot Wait to Be King!.' # 'Life is just a joker.'
    en = true
    homeTitleZh = 'Welcome to Wonderland'
    dark = true
    isSingleColumnOfPostList = true
    isShowPrevNextLink = true
    hasActiveAnimate = true
    hasActiveCool = true

# ğŸ¶ğŸ‰ğŸ‘€ğŸ’¡ğŸ‘“ğŸŒ
    [params.menu]
        [params.menu.00]
            active = true
            path = '/nav'
            zh = 'Navigation'
            icon = 'ğŸ¯'
        [params.menu.11]
            active = true
            path = '/posts'
            en = 'Posts'
            zh = 'Posts'
            icon = 'ğŸ“œ'
        [params.menu.33]
            active = true
            path = '/archive'
            zh = 'Archive'
            icon = 'ğŸ‰'
        [params.menu.44]
            active = true
            path = '/about'
            en = 'About'
            zh = 'About'
            icon = 'ğŸŒ' 
        [params.menu.55]
            active = true
            path = '/search'
            en = 'Search'
            zh = 'Search'
            icon = 'ğŸ”'

        # é¦–é¡µå›¾ç‰‡/æ–‡å­—
    
    [params.img]

        notImgButWords = false
        src = '1.jpg'
        width = 0
     [params.contact]
        icp = 'PuPu'             
        email = 'qb33@cornell.edu'
        github = 'Autumnbao279'            
        instagram = '279_is_bqy'          # e.g. https://www.instagram.com/loveminimal163
        color = '#696950'                        # å›¾æ ‡é¢œè‰²ï¼Œé»˜è®¤ä¸ºæµ…ç°è‰²
        slogan = 'Find me via : )'               # è”ç³»æ ‡è¯­ï¼Œä¸æƒ³æ˜¾ç¤ºï¼Œå¯ä»¥ç½®ç©º

# ä»¥ä¸‹ä¸º Markdown è§£ææ“çš„ä¸€äº›è®¾ç½®ï¼Œ
# å»ºè®®ä¿æŒä¸å˜
[markup]
    [markup.asciidocExt]
        preserveTOC = true
    [markup.highlight]
        # ä»£ç å—æ˜¾ç¤ºé£æ ¼ã€è¡Œå·æ˜¾ç¤º
        style = "github"
        lineNos = false
    [markup.tableOfContents]
        endLevel = 3
        ordered = false
        startLevel = 2
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

        

